declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_STEP_STAKING_MAINNET_PROGRAM_ID?: string;
    NEXT_PUBLIC_STEP_TOKEN_MINT_ADDRESS?: string;
    NEXT_PUBLIC_X_STEP_TOKEN_MINT_ADDRESS?: string;
    NEXT_PUBLIC_TOKEN_VAULT_ADDRESS?: string;
    NEXT_PUBLIC_TOKEN_VAULT_NONCE?: string;
    NEXT_PUBLIC_MAINNET_RPC?: string;
    NEXT_PUBLIC_MARKET_TOKEN_PRICE_API?: string;
  }
}
